spring.application.name=social-api

spring.datasource.url=jdbc:postgresql://localhost:5433/social_api
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=${JWT_SECRET:local-dev-secret-change-me-min-32-chars!!}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

app.auth.refresh-cookie-name=refresh_token
app.auth.refresh-cookie-path=/auth
app.auth.cookie-domain=
app.auth.cookie-secure=false
app.auth.cookie-same-site=Lax

auth.refresh-token.cleanup-retention-days=30
auth.refresh-token.cleanup-cron=0 30 3 * * *

post.soft-delete.retention-days=10
post.cleanup.cron=0 0 3 * * *

app.cors.allowed-origins=https://app.somedomain.com,http://localhost:3000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.upload.profile-pictures-dir=uploads/profile-pictures
app.upload.profile-pictures-url-prefix=/uploads/profile-pictures
app.upload.profile-picture-max-size=5242880